export const eventConfig = {
  eventName: 'ENGQUEST 5.0',
  organizer: 'Drushyam Photography Club',
  eyebrow: 'The campus is the map',
  tagline: 'The hunt begins here.',
  description: 'A multi-stage treasure hunt built for curious minds, sharp eyes, and teams that know how to follow a thread.',
  supportingCopy: 'Decode clues. Search the archive. Discover hidden locations. Reach the final quest.',
  eventDate: 'DATE TO BE ANNOUNCED',
  venue: 'VENUE TO BE ANNOUNCED',
  contact: 'CONTACT TO BE ANNOUNCED',
  qualificationNumbers: {
    registered: 'ALL',
    round1: 15,
    round2: 10,
    round3: 5,
    final: 3,
  },
  rounds: [
    { number: '01', title: 'Decode', label: 'The signal', description: 'Solve the first puzzle and earn the ten-digit key that opens the archive.' },
    { number: '02', title: 'Search', label: 'The archive', description: 'Enter the archive, follow the trail, and find what the pages leave unsaid.' },
    { number: '03', title: 'Discover', label: 'The location', description: 'Take the clue beyond the screen. The next answer is somewhere on campus.' },
    { number: '04', title: 'Clue', label: 'The extra clue', description: 'Enter the password to unlock a PDF clue.' },
    { number: '05', title: 'Track', label: 'The second location', description: 'Follow the new clue to the next campus location.' },
    { number: '06', title: 'Unveil', label: 'The final clue', description: 'Unlock the final PDF map with your 4-digit code.' },
    { number: '07', title: 'Final quest', label: 'The last light', description: 'The remaining teams race to the final location.' },
  ],
} as const
